# Site settings
title: "Quick Prototyping Summer school in Cambodia‑2016"
email: cambodiaschool@hidoba.com
url: https://cambodiaschool.org
description: "This was a free program for the best students to explore the most recent advances in programming, Artificial Intelligence and science. The course has taken place in Khemarak University, September 20–October 27, 2016 in Phnom Penh, the capital of Cambodia."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#FFFFFF'
  links: '#219ab3'

# Footer settings
footer: Vladimir Grankovsky

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
subscribe:
  - title: facebook
    url: https://www.facebook.com/cambodiaschool2016

social:
  - title: facebook
    url: https://www.facebook.com/cambodiaschool2016
  - title: linkedin
    url: https://www.linkedin.com/in/vladimir-grankovsky-44483b110


# Build settings
markdown: kramdown
permalink: pretty
